version: '2'

services:
  nginx-proxy:
    image: ${NGINX_PROXY_IMAGE:-docker-registry.ingotcloud.top/nginxproxy/nginx-proxy}:${NGINX_PROXY_VERSION:-1.8}
    container_name: ${NGINX_PROXY_CONTEINER_NAME:-nginx-proxy}
    restart: always
    networks:
      - extnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WORK_DIR}/volumes/conf:/etc/nginx/conf.d
      - ${WORK_DIR}/volumes/vhost:/etc/nginx/vhost.d
      - ${WORK_DIR}/volumes/html:/usr/share/nginx/html
      - ${WORK_DIR}/volumes/dhparam:/etc/nginx/dhparam
      - ${WORK_DIR}/volumes/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro


  acme-companion:
    image: ${ACME_COMPANION_IMAGE:-docker-registry.ingotcloud.top/nginxproxy/acme-companion}:${ACME_COMPANION_VERSION:-2.6}
    container_name: ${ACME_COMPANION_CONTEINER_NAME:-nginx-proxy-acme}
    restart: always
    networks:
      - extnet
    volumes_from:
      - ${NGINX_PROXY_CONTEINER_NAME:-nginx-proxy}
    volumes:
      - ${WORK_DIR}/volumes/certs:/etc/nginx/certs:rw
      - ${WORK_DIR}/volumes/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  extnet:
    name: ${DOCKER_NETWORK:-ingot-net}
    external: true
